server:
  port: 8090
  servlet:
    context-path: /
    jsp:
      init-parameters:
        development: true
        

spring:
  mvc:
    static-path-pattern: /resources/**/
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  h2:
    console:
      enabled: true
      path: /console

  datasource:
    #initialization-mode: always
    platform: h2
    #url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #url: jdbc:h2:file:./h2database;AUTO_SERVER=TRUE
    url: jdbc:h2:file:~/test
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    

    spring.jpa.hibernate.ddl-auto: none
    
mybatis:
  type-aliases-package: com.example.web.model




#logging:
#  level: com.example.web.model.mapper = TRACE
#    