DROP TABLE IF EXISTS BOARD;

CREATE TABLE BOARD (ID INT PRIMARY KEY AUTO_INCREMENT, SUBJECT VARCHAR, CONTENT VARCHAR);

INSERT INTO BOARD (SUBJECT, CONTENT) VALUES ('San Francisco', 'US');
INSERT INTO BOARD (SUBJECT, CONTENT) VALUES ('서울', 'KR');
INSERT INTO BOARD (SUBJECT, CONTENT) VALUES ('東京', 'JP');
INSERT INTO BOARD (SUBJECT, CONTENT) VALUES ('부산', 'KR');