DROP TABLE IF EXISTS BOARD;

CREATE TABLE BOARD (ID INT PRIMARY KEY AUTO_INCREMENT, SUBJECT VARCHAR, CONTENT VARCHAR);

INSERT INTO BOARD (SUBJECT, CONTENT) VALUES ('San Francisco', 'US');
INSERT INTO BOARD (SUBJECT, CONTENT) VALUES ('서울', 'KR');
INSERT INTO BOARD (SUBJECT, CONTENT) VALUES ('東京', 'JP');
INSERT INTO BOARD (SUBJECT, CONTENT) VALUES ('부산', 'KR');

DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE CATEGORY (CATEGORY_ID INT PRIMARY KEY AUTO_INCREMENT, CATEGORY_NAME VARCHAR);
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Makeup');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Skincare');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Fragrance');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Tools');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Bath & Body');

DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT (PRODUCT_ID INT PRIMARY KEY AUTO_INCREMENT, PRODUCT_NAME VARCHAR, PRODUCT_PRICE INT, PRODUCT_CATEGORY VARCHAR, PRODUCT_IMG VARCHAR);
INSERT INTO PRODUCT (PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CATEGORY, PRODUCT_IMG) VALUES ('SEPHORA COLLECTION Rouge Lacquer', 13, '1', '1');
INSERT INTO PRODUCT (PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CATEGORY, PRODUCT_IMG) VALUES ('BEAUTYBLENDER', 45, '1|4', '2');
INSERT INTO PRODUCT (PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CATEGORY, PRODUCT_IMG) VALUES ('JO MALONE LONDON Body Mist', 40, '3|5', '4');
INSERT INTO PRODUCT (PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CATEGORY, PRODUCT_IMG) VALUES ('FRESH Toner', 20, '2', '3');
INSERT INTO PRODUCT (PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CATEGORY, PRODUCT_IMG) VALUES ('HUDA BEAUTY Palette', 27, '1', '5');
INSERT INTO PRODUCT (PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CATEGORY, PRODUCT_IMG) VALUES ('SEPHORA COLLECTION Brush Set', 54, '1|4', '6');
INSERT INTO PRODUCT (PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CATEGORY, PRODUCT_IMG) VALUES ('BECCA Glow Kitchen Kit', 33, '1', '7');
INSERT INTO PRODUCT (PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CATEGORY, PRODUCT_IMG) VALUES ('GUCCI Eau de Toilette', 112, '3', '8');





