DROP TABLE IF EXISTS BOARD;

CREATE TABLE BOARD (ID INT PRIMARY KEY AUTO_INCREMENT, SUBJECT VARCHAR, CONTENT VARCHAR);

INSERT INTO BOARD (SUBJECT, CONTENT) VALUES ('San Francisco', 'US');
INSERT INTO BOARD (SUBJECT, CONTENT) VALUES ('서울', 'KR');
INSERT INTO BOARD (SUBJECT, CONTENT) VALUES ('東京', 'JP');
INSERT INTO BOARD (SUBJECT, CONTENT) VALUES ('부산', 'KR');

DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE CATEGORY (CATEGORY_ID VARCHAR(5) PRIMARY KEY, CATEGORY_NAME VARCHAR(50));
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES ('C00', 'ALL');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES ('C01', 'Makeup');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES ('C02', 'Skincare');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES ('C03', 'Fragrance');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES ('C04', 'Tools');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES ('C05', 'Bath & Body');

DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (PRODUCT_ID VARCHAR(5) PRIMARY KEY, PRODUCT_NAME VARCHAR(200), PRODUCT_PRICE INT, PRODUCT_CATEGORY_ID VARCHAR(200), PRODUCT_IMG VARCHAR(200));
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CATEGORY_ID, PRODUCT_IMG) VALUES ('P01', 'SEPHORA COLLECTION Rouge Lacquer', 13, 'C00|C01', '1');
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CATEGORY_ID, PRODUCT_IMG) VALUES ('P02', 'BEAUTYBLENDER', 45, 'C00|C01|C04', '2');
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CATEGORY_ID, PRODUCT_IMG) VALUES ('P03', 'JO MALONE LONDON Body Mist', 40, 'C00|C03|C05', '4');
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CATEGORY_ID, PRODUCT_IMG) VALUES ('P04', 'FRESH Toner', 20, 'C00|C02', '3');
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CATEGORY_ID, PRODUCT_IMG) VALUES ('P05', 'HUDA BEAUTY Palette', 27, 'C00|C01', '5');
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CATEGORY_ID, PRODUCT_IMG) VALUES ('P06', 'SEPHORA COLLECTION Brush Set', 54, 'C00|C01|C04', '6');
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CATEGORY_ID, PRODUCT_IMG) VALUES ('P07', 'BECCA Glow Kitchen Kit', 33, 'C00|C01', '7');
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CATEGORY_ID, PRODUCT_IMG) VALUES ('P08', 'GUCCI Eau de Toilette', 112, 'C00|C03', '8');





